severity: error
scss_files: css/**/*
linters:
  BemDepth:
    enabled: true
    max_elements: 1
  Comment:
    enabled: false
  DisableLinterReason:
    enabled: true
  LeadingZero:
    style: include_zero
  NestingDepth:
    max_depth: 5
    severity: warning
  PlaceholderInExtend:
    severity: warning
  PropertySortOrder:
    order:
      - content
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - flex
      - flex-basis
      - flex-grow
      - flex-shrink
      - align-self
      - display
      - flex-flow
      - flex-direction
      - flex-wrap
      - align-content
      - align-items
      - justify-content
      - order
      - visibility
      - float
      - clear
      - table-layout
      - border-collapse
      - empty-cells
      - box-sizing
      - object-fit
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - overflow
      - overflow-x
      - overflow-y
      - font
      - font-family
      - font-size
      - font-style
      - font-variant
      - font-weight
      - letter-spacing
      - line-height
      - list-style
      - list-style-image
      - list-style-position
      - list-style-type
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-shadow
      - text-transform
      - quotes
      - vertical-align
      - white-space
      - appearance
      - backface-visibility
      - background
      - background-attachment
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-size
      - border
      - border-color
      - border-radius
      - border-style
      - border-width
      - border-top
      - border-top-color
      - border-top-style
      - border-top-width
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-bottom
      - border-bottom-color
      - border-bottom-style
      - border-bottom-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - box-shadow
      - color
      - cursor
      - fill
      - fill-opacity
      - filter
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - opacity
      - pointer-events
      - stroke
      - stroke-alignment
      - stroke-dashadjust
      - stroke-dasharray
      - stroke-dashcorner
      - stroke-dashoffset
      - stroke-linecap
      - stroke-linejoin
      - stroke-miterlimit
      - stroke-opacity
      - stroke-width
      - transform
      - transform-origin
      - will-change
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - animation
      - animation-delay
      - animation-direction
      - animation-duration
      - animation-fill-mode
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
  SelectorFormat:
    convention: hyphenated_BEM
  SingleLinePerProperty:
    allow_single_line_rule_sets: false
  StringQuotes:
    severity: warning
  TrailingZero:
    enabled: true
  TransitionAll:
    enabled: true
    severity: warning
  VariableForProperty:
    enabled: true
    properties:
      - font
      - font-family
      - font-size
      - font-weight
      - z-index
